databases:
  - name: my_journal_api
    databaseName: my_journal_api
    user: my_journal_api

services:
  - type: web
    name: my_journal_api
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
